# Generated by Django 5.2.13 on 2026-04-21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('airquality', '0002_profile_two_factor_enabled_twofactortoken'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='email_verified',
            field=models.BooleanField(default=True),
        ),
    ]
