# Generated by Django 5.2.13 on 2026-05-18 19:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('airquality', '0005_unique_device_name_per_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='email_verified',
            field=models.BooleanField(default=False),
        ),
    ]
