# Generated by Django 5.2.13 on 2026-05-18 20:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('airquality', '0006_alter_profile_email_verified'),
    ]

    operations = [
        migrations.AddField(
            model_name='device',
            name='last_coordinates_received',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='device',
            name='latitude',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='device',
            name='longitude',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='sensorreading',
            name='latitude',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='sensorreading',
            name='longitude',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
