# Generated by Django 5.2.13 on 2026-05-18 20:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('airquality', '0007_device_last_coordinates_received_device_latitude_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='device',
            name='last_coordinates_received',
        ),
        migrations.RemoveField(
            model_name='device',
            name='latitude',
        ),
        migrations.RemoveField(
            model_name='device',
            name='longitude',
        ),
        migrations.RemoveField(
            model_name='sensorreading',
            name='latitude',
        ),
        migrations.RemoveField(
            model_name='sensorreading',
            name='longitude',
        ),
    ]
