# Generated by Django 5.2.13 on 2026-05-28 19:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('airquality', '0008_remove_device_last_coordinates_received_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='device',
            options={'ordering': ['-created_at']},
        ),
    ]
